### PR TITLE
web/queue/mempool.js: Highlight tooltip's hovered chart range.

### PR DESCRIPTION
**Pull request by cryptomental**
Highlight hovered chart range in the tooltip with a color corresponding to
the chart.

Issue: mempool/issues/14

### CODE REVIEW

**Comment by cryptomental** [comment]
Hi, I did not notice that you had it in test already and I started playing with it. I came up with a similar solution but with colors highlight instead of making it bold. Please merge or decline, whichever solution you prefer.

**Comment by cryptomental** [comment]
mempoolhighlight
An example how it looks like.

**Comment by jhoenicke** [comment]
I liked the idea of changing the background color.   I found it easier to add the code by hand to my changes.  I also changed the foreground color to white, as I found it better readable for most entries.

**Comment by cryptomental** [comment]
Great!

**Pull request closed without merging**
